#!/bin/sh

echo "sdk.dir=$1" >local.properties

git clone -b master https://github.com/kontalk/client-common-java.git &&
cd client-common-java &&
./setup asmack &&
cd ..

git clone https://github.com/kontalk/emojicon.git
